language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - vendor/bundle
rvm:
  - &ruby24 2.4
  - &ruby23 2.3
  - &jruby jruby-9.1.12.0
  - &rhead ruby-head
env:
  matrix:
    - LIQUID_VERSION="~> 4.0"
    - LIQUID_VERSION="~> 3.0"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: *jruby
    - rvm: *rhead
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: change
